# Generated by Django 4.2.27 on 2025-12-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='deadline',
            new_name='deadline',
        ),
    ]
